n = int(input("Digite um número: "))
n2 = int(input("Digite um número: "))

print("add: ", n + n2)
print("sub:", n - n2)
print("mult:", n * n2)
print("div:", n / n2)
print("div int:", n // n2)
print("rest div:", n % n2)
print("pot:", n ^ n2)