# Lista de palavras para o jogo da forca
palavras = [
    "cachorro",    # Fácil
    "gato",        # Muito fácil
    "banana",      # Fácil
    "professor",   # Médio
    "astronauta",  # Difícil
    "elefante",    # Médio
    "bicicleta",   # Médio
    "computador",  # Difícil
    "casa",        # Muito fácil
    "livro",       # Fácil
    "hipopótamo",  # Difícil
    "televisão",   # Médio
    "cachoeira",   # Difícil
    "dinossauro",  # Difícil
    "lápis",       # Fácil
    "floresta",    # Médio
    "universidade",# Difícil
    "relógio",     # Médio
    "mar",         # Muito fácil
    "caderno",     # Fácil
    "geleira",     # Difícil
    "coelho",      # Fácil
    "oceano",      # Médio
    "ferrovia",    # Difícil
    "xadrez",      # Médio
    "banana",      # Fácil
    "mariposa",    # Difícil
    "sol",         # Muito fácil
    "abacaxi",     # Médio
    "coruja",      # Fácil
    "jacaré",      # Médio
    "lagartixa",   # Difícil
    "jardim",      # Fácil
    "morcego",     # Médio
    "sanduíche",   # Médio
    "escalada",    # Difícil
    "tartaruga",   # Difícil
    "vampiro",     # Médio
    "golfinho",    # Médio
    "tigela",      # Fácil
    "roda",        # Fácil
    "flamingo",    # Difícil
    "papagaio",    # Médio
    "eletricidade",# Difícil
    "lua",         # Muito fácil
    "melancia",    # Médio
    "estrela",     # Médio
    "cartão",      # Fácil
    "pneumonia",   # Difícil
    "mosquito",    # Médio
    "amarelo",     # Fácil
    "cinema",      # Fácil
    "internet",    # Médio
    "orquestra",   # Difícil
    "pizza",       # Fácil
    "mágico",      # Médio
    "telefone",    # Médio
    "espelho",     # Médio
    "borboleta",   # Difícil
    "sandália",    # Fácil
    "pirata",      # Fácil
    "diamante",    # Difícil
    "helicóptero", # Difícil
    "esquilo",     # Médio
    "trem",        # Muito fácil
    "camelo",      # Fácil
    "máquina",     # Médio
    "tigre",       # Médio
    "vulcão",      # Médio
    "guitarra",    # Médio
    "fantasma",    # Médio
    "cebola",      # Fácil
    "morango",     # Médio
    "jacaré",      # Médio
    "dicionário",  # Difícil
    "casaco",      # Fácil
    "jornal",      # Fácil
    "canguru",     # Médio
    "nuvem",       # Fácil
    "foguete",     # Médio
    "pirâmide",    # Difícil
    "gira",        # Fácil
    "planta",      # Fácil
    "geladeira",   # Difícil
    "banco",       # Fácil
    "iguana",      # Médio
    "circuito",    # Médio
    "eleição",     # Médio
    "desafio",     # Médio
    "morcego",     # Médio
    "espantalho",  # Difícil
    "príncipe",    # Médio
    "ralo",        # Fácil
    "ferradura",   # Médio
    "macaco",      # Fácil
    "baleia",      # Médio
    "gira",        # Fácil
    "morango",     # Médio
    "centopeia",   # Difícil
    "corrente",    # Médio
    "janela",      # Fácil
    "estrela",     # Médio
    "esqueleto",   # Difícil
    "quadro",      # Fácil
    "escultura",   # Difícil
    "tigre",       # Médio
    "geladeira",   # Difícil
    "lama",        # Fácil
    "velocidade",  # Difícil
    "livro",       # Fácil
    "granizo",     # Médio
    "tapete",      # Médio
    "aeroporto",   # Médio
    "celular",     # Fácil
    "caderno",     # Fácil
    "foca",        # Fácil
    "terremoto",   # Médio
    "joaninha",    # Médio
    "cartão",      # Fácil
    "tulipa",      # Fácil
    "hipótese",    # Difícil
    "montanha",    # Médio
    "torradeira",  # Difícil
    "lanterna",    # Médio
    "cachoeira",   # Difícil
    "miragem",     # Médio
    "abóbora",     # Médio
    "pirata",      # Fácil
    "jacaré",      # Médio
    "barco",       # Fácil
    "formiga",     # Fácil
    "crocodilo",   # Médio
    "lagartixa",   # Difícil
    "astronauta",  # Difícil
    "macaco",      # Fácil
    "geleira",     # Difícil
    "flauta",      # Médio
    "borboleta",   # Difícil
    "antártica",   # Difícil
    "planície",    # Médio
    "horizonte",   # Médio
    "gelo",        # Fácil
    "abacate",     # Médio
    "desenho",     # Médio
    "almofada",    # Médio
    "castelo",     # Médio
    "girassol",    # Médio
    "bruxa",       # Fácil
    "camiseta",    # Médio
    "ursinho",     # Médio
    "floresta",    # Médio
    "telescópio",  # Difícil
    "oceano",      # Médio
    "máquina",     # Médio
    "trator",      # Médio
    "panqueca",    # Médio
    "sol",         # Muito fácil
    "futebol",     # Médio
    "piscina",     # Médio
    "ventilador",  # Difícil
    "melancia",    # Médio
    "papagaio",    # Médio
    "sombra",      # Médio
    "balão",       # Fácil
    "chocolate",   # Médio
    "pijama",      # Médio
    "relâmpago",   # Difícil
    "planeta",     # Médio
    "granizo",     # Médio
    "milho",       # Fácil
    "cachorro",    # Fácil
    "marinheiro",  # Médio
    "pinguim",     # Médio
    "pantera",     # Médio
    "ferrovia",    # Difícil
    "teclado",     # Médio
    "pimenta",     # Médio
    "camarão",     # Médio
    "raposa",      # Médio
    "viagem",      # Médio
    "urso",        # Fácil
    "vento",       # Fácil
    "cogumelo",    # Médio
    "submarino",   # Difícil
    "galáxia",     # Médio
    "tigela",      # Fácil
    "tartaruga",   # Difícil
]
